### PR TITLE
Add support for BitmapLayer._imageCoordinateSystem

### PR DESCRIPTION
**Pull request by zakjan**
New code from https://github.com/visgl/deck.gl/pull/5154 is duplicated here. It would be great to automatically support such BitmapLayer features without duplication though.

### CODE REVIEW

**Comment by zakjan** [comment]
Update: forced precision of coordinateConversion uniform to prevent conflicts with different precision in fs and vs.

**Review by kylebarron — APPROVED** [review]

**Comment by kylebarron** [comment]
> It would be great to automatically support such BitmapLayer features without duplication though.

I don't see a clear way to reuse the BitmapLayer shaders directly. Also the BitmapLayer only has WebGL1 shaders, whereas it can be useful to also have a set of WebGL2 shaders.

**Comment by zakjan** [comment]
Have you considered using LayerExtension instead of subclassing? I'm exploring https://github.com/visgl/deck.gl/blob/master/modules/geo-layers/src/mvt-layer/clip-extension.js just now, it seems as an interesting concept.

**Comment by kylebarron** [comment]
> Have you considered using LayerExtension instead of subclassing?

I didn't know before that it was possible to inject shader code at any line, but that still doesn't solve the WebGL 1 vs 2 shader problem. The `BitmapLayer` shaders are only in WebGL1, and if I recall correctly you can't use any WebGL2 features unless you use WebGL2 shaders. So I don't see an easy way to use WebGL2 features with layer extensions.

**Comment by zakjan** [comment]
That's true. However, I thought that deck.gl is aimed to be WebGL2-first, so the possible way would be to update BitmapLayer shaders to WebGL2? It seems that WebGL1 compatibility is maintained with luma.gl transpileToGLSL100 option.

**Comment by kylebarron** [comment]
You could create an issue about that. It seems various layers use either WebGL1 or WebGL2 shaders. For example the Mesh layer in deck uses WebGL2 shaders while the BitmapLayer uses WebGL1 shaders. It could be that maintainers are receptive to the idea of moving to WebGL2 shaders and using `transpileToGLSL100` as needed, but that no one has put in the effort yet. I don't know.

**Pull request merged**
